// Vulnerable snippets for the Taint Flow Lab.
// `nodes` is a trimmed AST (parent links), `taint` is the data-flow path source → sink,
// `patch` removes/adds lines by original line number.
export const labSamples = [
  {
    id: "c-bof",
    lang: "C",
    file: "net/packet.c",
    cwe: "CWE-120",
    severity: "HIGH",
    confidence: "0.98",
    time: "0.38",
    code: [
      { n: 38, t: "void process_packet(const char *input) {", role: "source" },
      { n: 39, t: "    char buf[64];" },
      { n: 40, t: "    size_t len = strlen(input);" },
      { n: 41, t: "    strcpy(buf, input);", role: "sink" },
      { n: 42, t: '    log_info("pkt=%s len=%zu", buf, len);' },
      { n: 43, t: "}" },
    ],
    patch: {
      remove: [41],
      add: [{ after: 41, t: '    snprintf(buf, sizeof(buf), "%s", input);' }],
    },
    nodes: [
      { id: "fn", label: "FunctionDecl process_packet" },
      { id: "param", label: "ParmVarDecl input", parent: "fn", role: "source" },
      { id: "body", label: "CompoundStmt", parent: "fn" },
      { id: "buf", label: "VarDecl buf[64]", parent: "body" },
      { id: "len", label: "VarDecl len", parent: "body" },
      { id: "call", label: "CallExpr strcpy", parent: "body", role: "sink" },
      { id: "log", label: "CallExpr log_info", parent: "body" },
      { id: "dst", label: "DeclRef buf", parent: "call" },
      { id: "src", label: "DeclRef input", parent: "call" },
    ],
    taint: ["param", "src", "call"],
    sanitizer: "snprintf · sizeof(buf)",
    textKey: "s1",
  },
  {
    id: "cpp-uaf",
    lang: "C++",
    file: "core/session.cpp",
    cwe: "CWE-416",
    severity: "HIGH",
    confidence: "0.95",
    time: "0.41",
    code: [
      { n: 114, t: "void cleanup_session(Session* s) {" },
      { n: 115, t: "    audit_log(s->id);" },
      { n: 116, t: "    delete s;", role: "source" },
      { n: 117, t: "    metrics.inc(\"closed\");" },
      { n: 118, t: "    s->last_ping = now();", role: "sink" },
      { n: 119, t: "}" },
    ],
    patch: {
      remove: [118],
      add: [
        { after: 115, t: "    s->last_ping = now();" },
        { after: 116, t: "    s = nullptr;" },
      ],
    },
    nodes: [
      { id: "fn", label: "FunctionDecl cleanup_session" },
      { id: "param", label: "ParmVarDecl s", parent: "fn" },
      { id: "body", label: "CompoundStmt", parent: "fn" },
      { id: "audit", label: "CallExpr audit_log", parent: "body" },
      { id: "del", label: "CXXDeleteExpr s", parent: "body", role: "source" },
      { id: "inc", label: "CXXMemberCall inc", parent: "body" },
      { id: "assign", label: "BinaryOperator =", parent: "body" },
      { id: "member", label: "MemberExpr s->last_ping", parent: "assign", role: "sink" },
      { id: "call", label: "CallExpr now", parent: "assign" },
    ],
    taint: ["param", "del", "member"],
    sanitizer: "lifetime · s = nullptr",
    textKey: "s2",
  },
  {
    id: "py-sqli",
    lang: "Python",
    file: "api/users.py",
    cwe: "CWE-89",
    severity: "CRITICAL",
    confidence: "0.99",
    time: "0.22",
    code: [
      { n: 14, t: '@app.route("/user")' },
      { n: 15, t: "def get_user():" },
      { n: 16, t: '    uid = request.args.get("id")', role: "source" },
      { n: 17, t: '    q = f"SELECT * FROM users WHERE id = {uid}"' },
      { n: 18, t: "    return db.execute(q).fetchone()", role: "sink" },
    ],
    patch: {
      remove: [17, 18],
      add: [
        { after: 18, t: '    q = "SELECT * FROM users WHERE id = ?"' },
        { after: 18, t: "    return db.execute(q, (uid,)).fetchone()" },
      ],
    },
    nodes: [
      { id: "fn", label: "FunctionDef get_user" },
      { id: "a1", label: "Assign uid", parent: "fn" },
      { id: "get", label: "Call request.args.get", parent: "a1", role: "source" },
      { id: "a2", label: "Assign q", parent: "fn" },
      { id: "fstr", label: "JoinedStr f\"…{uid}\"", parent: "a2" },
      { id: "ret", label: "Return", parent: "fn" },
      { id: "exec", label: "Call db.execute", parent: "ret", role: "sink" },
      { id: "q", label: "Name q", parent: "exec" },
    ],
    taint: ["get", "a1", "fstr", "q", "exec"],
    sanitizer: "bind params · ?",
    textKey: "s3",
  },
  {
    id: "go-cmdi",
    lang: "Go",
    file: "cmd/diag/ping.go",
    cwe: "CWE-78",
    severity: "CRITICAL",
    confidence: "0.97",
    time: "0.29",
    code: [
      { n: 21, t: "func pingHost(w http.ResponseWriter, r *http.Request) {" },
      { n: 22, t: '    host := r.URL.Query().Get("host")', role: "source" },
      { n: 23, t: '    out, _ := exec.Command("sh", "-c", "ping -c1 "+host).Output()', role: "sink" },
      { n: 24, t: "    w.Write(out)" },
      { n: 25, t: "}" },
    ],
    patch: {
      remove: [23],
      add: [
        { after: 22, t: '    if !hostRe.MatchString(host) { http.Error(w, "bad host", 400); return }' },
        { after: 23, t: '    out, _ := exec.Command("ping", "-c1", host).Output()' },
      ],
    },
    nodes: [
      { id: "fn", label: "FuncDecl pingHost" },
      { id: "body", label: "BlockStmt", parent: "fn" },
      { id: "a1", label: "AssignStmt host", parent: "body" },
      { id: "get", label: "CallExpr Query().Get", parent: "a1", role: "source" },
      { id: "a2", label: "AssignStmt out", parent: "body" },
      { id: "exec", label: "CallExpr exec.Command", parent: "a2", role: "sink" },
      { id: "concat", label: "BinaryExpr +", parent: "exec" },
      { id: "write", label: "CallExpr w.Write", parent: "body" },
    ],
    taint: ["get", "a1", "concat", "exec"],
    sanitizer: "allowlist · argv",
    textKey: "s4",
  },
];
